[general]
dir = "~/temp/dotfiles"

[dotfiles]
wezterm = "~/.wezterm.lua"
fish = "~/.config/fish"
ghostty = "~/.config/ghostty"
karabiner = "~/.config/karabiner/karabiner.json"
lvim = "~/.config/lvim"
